name: Validate PR

on:
  pull_request:
    branches: [master]

jobs:
  publish_extensions:
    env:
      VALIDATE_PR: true
      SKIP_PUBLISH: true
      FORCE: true
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.3.0
        with:
          node-version: "18.x"
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: npm install
      - run: npm i -g @vscode/vsce pnpm
      - name: Set up pyenv
        uses: "gabrielfalcao/pyenv-action@32ef4d2c861170ce17ded56d10329d83f4c8f797"
        with:
            command: python --version
      - name: Set default global version
        run: |
          pyenv install 3.8
          pyenv global 3.8
      - run: EXTENSIONS=$(node diff-extensions) node publish-extensions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Report results
        run: bun run ./report-extensions.ts
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: |
            /tmp/stat.json
            /tmp/result.md
      - name: Upload job summary
        run: cat /tmp/result.md >> $GITHUB_STEP_SUMMARY
      - name: Save PR number to file
        if: github.event_name == 'pull_request'
        run: echo ${{ github.event.number }} > PR_NUMBER.txt
      - name: Archive PR number
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: PR_NUMBER
          path: PR_NUMBER.txt


